package com.rss.common;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement
@DynamoDBTable(tableName = "jobs")
public class Job {
	
	private int mJobId;
	private String mURL;
	
	@DynamoDBAutoGeneratedKey
	public int getJobId(){
		return mJobId;
	}
	
	public void setJobId(int jobId) {
		mJobId = jobId;
	}
	
	@DynamoDBHashKey
	@DynamoDBAttribute
	public String getURL() {
		return mURL;
	}

	public void setURL(String url) {
		mURL = url;
	}
}
