package com.rss.common.dataprovider;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement
@DynamoDBTable(tableName = "jobs")
public class JobObjectMapper {
	
	private String jobId;
	private Date requestTimestamp;
	private String url;
	
	@DynamoDBAutoGeneratedKey
	public String getJobId(){
		return jobId;
	}
	
	public void setJobId(String jobId) {
		this.jobId = jobId;
	}	

	@DynamoDBAttribute
	public Date getRequestTimestamp() {
		return requestTimestamp;
	}

	public void setRequestTimestamp(Date requestTimestamp) {
		this.requestTimestamp = requestTimestamp;
	}	
	
	@DynamoDBHashKey
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
}
